version: 2
project_name: whats-flying-over-me

builds:
  - id: wfo
    main: ./cmd/whats-flying-over-me
    binary: whats-flying-over-me
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

# Docker builds - only when GITHUB_REPOSITORY is available
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - README.md
      - LICENSE 
