version: 2
project_name: whats-flying-over-me

builds:
  - id: wfo
    main: ./cmd/whats-flying-over-me
    binary: whats-flying-over-me
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

# Docker builds - only when GITHUB_REPOSITORY is available
dockers:
  - ids:
      - wfo
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    use: buildx
