blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://github.com/benvon/ai-code-template-go/discussions
    about: Please ask and answer questions here.
  - name: Security Issues
    url: mailto:security@example.com
    about: Please report security vulnerabilities via email.
