name: quality

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    uses: benvon/reusable-workflows/.github/workflows/go-quality.yml@130a938eed408977d8c3159327f13306f422b1eb
    with:
      quality_command: |
        make all
        go build -v ./...
      coverage_file: coverage.out
      upload_codecov: true
      codecov_flags: unittests
      codecov_name: codecov-umbrella
