name: release-policy

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  release-policy:
    uses: benvon/reusable-workflows/.github/workflows/release-policy.yml@35c37bc452dc991c2c8cc88c4fc48e4d7f0e0aaf
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
