name: release-policy

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  release-policy:
    uses: benvon/reusable-workflows/.github/workflows/release-policy.yml@35c37bc4b4c72570ce464c783a71ec3d03c45d15
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
