name: release-policy

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review, labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  release-policy:
    uses: benvon/reusable-workflows/.github/workflows/release-policy.yml@f70796de0a6527dbed267a64835c3cc81b8144e0
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
