name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-rc*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test ./...

      - name: Check GH_TOKEN secret
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "❌ GH_TOKEN secret is not set!"
            echo "Please add GH_TOKEN secret to your repository secrets."
            echo "This token needs write:packages permission to publish Docker images."
            exit 1
          else
            echo "✅ GH_TOKEN secret is available"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Use PAT for package publishing permissions
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Ensure proper Docker authentication
          DOCKER_REGISTRY: ghcr.io
