name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: benvon/reusable-workflows/.github/workflows/go-goreleaser-release.yml@35c37bc452dc991c2c8cc88c4fc48e4d7f0e0aaf
